default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

dev_and_test: &dev_and_test
  host: <%= ENV['DATABASE_HOST'] || "localhost" %>
  username: postgres

development:
  <<: *default
  <<: *dev_and_test
  database: teacher_den_development

test:
  <<: *default
  <<: *dev_and_test
  database: teacher_den_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
