vars:
  site_title_first: TEACHER'S
  site_title_last: DEN
  site_title_anecdote: "A wise teacher makes learning a joy"

  root_title: "Accueil"
  colles_title: "Colles"
  infos_title: "Informations"
  downloads_title: "Téléchargements"

  bottom_anecdote: "Design by Xiaoying Riley"
