default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

dev_and_test: &dev_and_test
  host: localhost
  username: dev
  password: dev

development:
  <<: *default
  <<: *dev_and_test
  database: teacher_den_development

test:
  <<: *default
  <<: *dev_and_test
  database: teacher_den_test

production:
  <<: *default
  host:     <%= ENV['DATABASE_HOST'] %>
  port:     <%= ENV['DATABASE_PORT'] %>
  database: <%= ENV['DATABASE_SCHEMA'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
